let livres = [
    {
        idOurage: 1,
        titre: "Le Seigneur des Anneaux : La Communauté de l'Anneau",
        nbPages: 576,
        extrait: "Un Anneau pour les gouverner tous...",
        resume: "Frodon le Hobbit hérite de l'Anneau Unique et part avec une communauté pour détruire ce mal ancien.",
        anneeEdition: 1954,
        moyenneAppreciation: 4.8,
        imageCouverture: "lotr1.jpg",
        idCategorie: 1,
        idAuteur: 1,
        idEditeur: 1,
    },
    {
        idOurage: 2,
        titre: "1984",
        nbPages: 328,
        extrait: "Big Brother vous regarde.",
        resume: "Dans une dystopie totalitaire, Winston Smith tente de résister à un régime qui contrôle la pensée.",
        anneeEdition: 1949,
        moyenneAppreciation: 4.6,
        imageCouverture: "1984.jpg",
        idCategorie: 1,
        idAuteur: 2,
        idEditeur: 2,
    },
    {
        idOurage: 3,
        titre: "Harry Potter à l'école des sorciers",
        nbPages: 309,
        extrait: "Tu es un sorcier, Harry.",
        resume: "Harry découvre qu’il est un sorcier et entre à Poudlard, une école de magie pleine de mystères.",
        anneeEdition: 1997,
        moyenneAppreciation: 4.7,
        imageCouverture: "hp1.jpg",
        idCategorie: 2,
        idAuteur: 3,
        idEditeur: 3,
    },
    {
        idOurage: 4,
        titre: "Le Petit Prince",
        nbPages: 96,
        extrait: "On ne voit bien qu’avec le cœur.",
        resume: "Un aviateur rencontre un petit prince venu d’une autre planète qui lui partage sa vision de la vie.",
        anneeEdition: 1943,
        moyenneAppreciation: 4.9,
        imageCouverture: "petitprince.jpg",
        idCategorie: 3,
        idAuteur: 4,
        idEditeur: 4,
    },
    {
        idOurage: 5,
        titre: "L'Étranger",
        nbPages: 123,
        extrait: "Aujourd’hui, maman est morte.",
        resume: "Meursault, un homme détaché, tue un homme et est jugé non pour le meurtre, mais pour son indifférence.",
        anneeEdition: 1942,
        moyenneAppreciation: 4.3,
        imageCouverture: "etranger.jpg",
        idCategorie: 4,
        idAuteur: 5,
        idEditeur: 5,
    },
	{
		idOurage: 6,
		titre: "Le Seigneur des Anneaux : Les Deux Tours",
		nbPages: 656,
		extrait: "Il y a une autre voie, plus sombre...",
		resume: "La communauté est dispersée. Frodon continue sa quête vers le Mordor accompagné de Sam et Gollum.",
		anneeEdition: 1954,
		moyenneAppreciation: 4.7,
		imageCouverture: "lotr2.jpg",
		idCategorie: 1,
		idAuteur: 1,
		idEditeur: 1,
	},
	{
		idOurage: 7,
		titre: "Le Seigneur des Anneaux : Le Retour du Roi",
		nbPages: 624,
		extrait: "La guerre pour l'Anneau commence...",
		resume: "La guerre atteint son apogée tandis que Frodon s'approche de la Montagne du Destin.",
		anneeEdition: 1955,
		moyenneAppreciation: 4.9,
		imageCouverture: "lotr3.jpg",
		idCategorie: 1,
		idAuteur: 1,
		idEditeur: 1,
	},
	{
		idOurage: 8,
		titre: "Le Hobbit",
		nbPages: 310,
		extrait: "Au fond d’un trou vivait un hobbit...",
		resume: "Bilbo Baggins est entraîné dans une aventure épique pour aider des nains à récupérer leur trésor volé par un dragon.",
		anneeEdition: 1937,
		moyenneAppreciation: 4.8,
		imageCouverture: "hobbit.jpg",
		idCategorie: 1,
		idAuteur: 1,
		idEditeur: 1,
	},
	{
		idOurage: 9,
		titre: "Harry Potter et la Chambre des Secrets",
		nbPages: 341,
		extrait: "Les murs de l’école chuchotent…",
		resume: "Harry retourne à Poudlard où un mystère ancien menace les élèves.",
		anneeEdition: 1998,
		moyenneAppreciation: 4.6,
		imageCouverture: "hp2.jpg",
		idCategorie: 2,
		idAuteur: 3,
		idEditeur: 3,
	},
	{
		idOurage: 10,
		titre: "Harry Potter et le Prisonnier d’Azkaban",
		nbPages: 435,
		extrait: "Le traître est parmi eux...",
		resume: "Harry découvre la vérité sur Sirius Black et sur son passé familial.",
		anneeEdition: 1999,
		moyenneAppreciation: 4.7,
		imageCouverture: "hp3.jpg",
		idCategorie: 2,
		idAuteur: 3,
		idEditeur: 3,
	},
	{
		idOurage: 11,
		titre: "Animal Farm",
		nbPages: 112,
		extrait: "Tous les animaux sont égaux, mais certains sont plus égaux que d'autres.",
		resume: "Une ferme devient le théâtre d'une révolution animale aux relents totalitaires.",
		anneeEdition: 1945,
		moyenneAppreciation: 4.4,
		imageCouverture: "animalfarm.jpg",
		idCategorie: 4,
		idAuteur: 2,
		idEditeur: 2,
	},
	{
		idOurage: 12,
		titre: "La Peste",
		nbPages: 308,
		extrait: "Il est aussi naturel que la peste revienne.",
		resume: "Une ville algérienne frappée par une épidémie devient le reflet de l’absurdité humaine.",
		anneeEdition: 1947,
		moyenneAppreciation: 4.5,
		imageCouverture: "lapeste.jpg",
		idCategorie: 4,
		idAuteur: 5,
		idEditeur: 5,
	},
	{
		idOurage: 13,
		titre: "Terre des hommes",
		nbPages: 224,
		extrait: "L’homme se découvre quand il se mesure avec l’obstacle.",
		resume: "Réflexions sur l'humanité, l'amitié, la guerre et le sens de la vie à travers l'aviation.",
		anneeEdition: 1939,
		moyenneAppreciation: 4.3,
		imageCouverture: "terredeshommes.jpg",
		idCategorie: 3,
		idAuteur: 4,
		idEditeur: 4,
	},
	{
		idOurage: 14,
		titre: "Harry Potter et la Coupe de Feu",
		nbPages: 636,
		extrait: "Le Tournoi des Trois Sorciers va commencer !",
		resume: "Harry est choisi mystérieusement pour participer à un tournoi magique dangereux.",
		anneeEdition: 2000,
		moyenneAppreciation: 4.8,
		imageCouverture: "hp4.jpg",
		idCategorie: 2,
		idAuteur: 3,
		idEditeur: 3,
	},
	{
		idOurage: 15,
		titre: "Les Enfants de Minuit",
		nbPages: 647,
		extrait: "Je suis né à minuit, le jour de l'indépendance de l'Inde...",
		resume: "Saleem Sinai, doté de pouvoirs spéciaux, raconte l’histoire de sa vie mêlée à celle de son pays.",
		anneeEdition: 1981,
		moyenneAppreciation: 4.2,
		imageCouverture: "enfantsminuit.jpg",
		idCategorie: 4,
		idAuteur: 6,
		idEditeur: 6,
	},
	{
		idOurage: 16,
		titre: "À la recherche du temps perdu - Du côté de chez Swann",
		nbPages: 468,
		extrait: "Longtemps, je me suis couché de bonne heure.",
		resume: "Une plongée dans la mémoire involontaire à travers les souvenirs d'enfance de Marcel.",
		anneeEdition: 1913,
		moyenneAppreciation: 4.4,
		imageCouverture: "swann.jpg",
		idCategorie: 4,
		idAuteur: 7,
		idEditeur: 7,
	},
	{
		idOurage: 17,
		titre: "Crime et Châtiment",
		nbPages: 576,
		extrait: "C’est dans la souffrance seule qu’on peut trouver la conscience.",
		resume: "Un jeune étudiant russe commet un meurtre et est consumé par sa conscience.",
		anneeEdition: 1866,
		moyenneAppreciation: 4.6,
		imageCouverture: "crimechatiment.jpg",
		idCategorie: 4,
		idAuteur: 8,
		idEditeur: 8,
	},
	{
		idOurage: 18,
		titre: "Les Frères Karamazov",
		nbPages: 824,
		extrait: "Si Dieu n'existe pas, tout est permis.",
		resume: "Un drame familial mêlant foi, morale, et philosophie dans la Russie du XIXe siècle.",
		anneeEdition: 1880,
		moyenneAppreciation: 4.8,
		imageCouverture: "karamazov.jpg",
		idCategorie: 4,
		idAuteur: 8,
		idEditeur: 8,
	},
	{
		idOurage: 19,
		titre: "Madame Bovary",
		nbPages: 432,
		extrait: "Elle voulait mourir, et elle voulait vivre à Paris.",
		resume: "Emma Bovary, insatisfaite, cherche l’évasion à travers l’amour et le luxe.",
		anneeEdition: 1857,
		moyenneAppreciation: 4.3,
		imageCouverture: "bovary.jpg",
		idCategorie: 4,
		idAuteur: 9,
		idEditeur: 9,
	},
	{
		idOurage: 20,
		titre: "Fahrenheit 451",
		nbPages: 256,
		extrait: "Il était une joie de brûler.",
		resume: "Dans un futur où lire est interdit, un pompier se rebelle contre le système.",
		anneeEdition: 1953,
		moyenneAppreciation: 4.5,
		imageCouverture: "fahrenheit451.jpg",
		idCategorie: 4,
		idAuteur: 10,
		idEditeur: 10,
	},
	{
		idOurage: 21,
		titre: "Les Misérables",
		nbPages: 1488,
		extrait: "Même la nuit la plus sombre prendra fin et le soleil se lèvera.",
		resume: "Jean Valjean, ancien forçat, cherche la rédemption dans une France bouleversée.",
		anneeEdition: 1862,
		moyenneAppreciation: 4.7,
		imageCouverture: "miserables.jpg",
		idCategorie: 4,
		idAuteur: 11,
		idEditeur: 11,
	},
	{
		idOurage: 22,
		titre: "L’Odyssée",
		nbPages: 541,
		extrait: "Chante, déesse, l’homme aux mille ruses...",
		resume: "Le long retour d’Ulysse vers Ithaque après la guerre de Troie.",
		anneeEdition: -800,
		moyenneAppreciation: 4.6,
		imageCouverture: "odyssee.jpg",
		idCategorie: 4,
		idAuteur: 12,
		idEditeur: 12,
	},
	{
		idOurage: 23,
		titre: "Le Nom de la rose",
		nbPages: 552,
		extrait: "Stat rosa pristina nomine, nomina nuda tenemus.",
		resume: "Un moine enquête sur une série de meurtres mystérieux dans une abbaye médiévale.",
		anneeEdition: 1980,
		moyenneAppreciation: 4.5,
		imageCouverture: "nomdelarose.jpg",
		idCategorie: 1,
		idAuteur: 13,
		idEditeur: 13,
	},
	{
		idOurage: 24,
		titre: "Le Meilleur des mondes",
		nbPages: 311,
		extrait: "Tout le monde appartient à tout le monde.",
		resume: "Dans un monde eugéniste et consumériste, un homme doute de la perfection de son époque.",
		anneeEdition: 1932,
		moyenneAppreciation: 4.4,
		imageCouverture: "meilleurmonde.jpg",
		idCategorie: 4,
		idAuteur: 14,
		idEditeur: 14,
	},
	{
		idOurage: 25,
		titre: "Le Comte de Monte-Cristo",
		nbPages: 1312,
		extrait: "L’attente et l’espérance...",
		resume: "Edmond Dantès, trahi, s’échappe de prison et prépare sa vengeance.",
		anneeEdition: 1844,
		moyenneAppreciation: 4.9,
		imageCouverture: "montecristo.jpg",
		idCategorie: 4,
		idAuteur: 15,
		idEditeur: 15,
	}	
];

export { livres };
